### ISSUE TITLE
Finish Creating Assets.

### ISSUE THREAD

**Issue by jackdweber** [EECS448-KitchenUtensils/DefinitelyNotProject3#1]
The asset folder already has the chess pieces and board squares, but we need

* blue board squares (For move depiction.)
* Buttons (Probably one good one bad.)
* More may come.

**Comment by zjcers** [comment]
Moved this to the Desktop Client milestone where it belongs.

**Comment by zjcers** [comment]
For Project 3, this is complete. Closing
