### ISSUE TITLE
Make board show possible moves

### ISSUE THREAD

**Issue by twalenczyk** [EECS448-KitchenUtensils/DefinitelyNotProject3#10]
When a player selects one of their pieces, it should show the player the possible moves for that piece. This can be accomplished by changing the color of the square to which the piece can move. 

If it's currently the player's turn, it should show only valid moves and the squares should turn blue. If it is not the player's turn, it should show all possible moves for the piece and the squares should turn orange.

This will require
- Assets for the squares
- A function to find valid squares
- A function to change the squares

**Comment by zjcers** [comment]
This is implemented, but needs testing as tracked in #8
