### ISSUE TITLE
Ambiguous Piece Ownership

### ISSUE THREAD

**Issue by twalenczyk** [EECS448-KitchenUtensils/DefinitelyNotProject3#14]
Currently, to do this, you must specify the piece. However, to instantiate the proper backend object, you must also specify the owner and the position of the piece. However, when the board is created, at no point is the owner of a piece specified. This can be rectified by specifying the owner during the board generation phase.

**Comment by zjcers** [comment]
This is already done. I'll go ahead and hide the constructors for all of the objects that you shouldn't be making yourself.

**Comment by zjcers** [comment]
Fixed in 194088df610ee1703684a1fbecc4a1e0851140bf Creating a ChessGame object creates the pieces so the constructors for the pieces shouldn't be accessed outside of GameModel
