### ISSUE TITLE
Possible Moves Lambda Function -- Pawn

### ISSUE THREAD

**Issue by twalenczyk** [EECS448-KitchenUtensils/DefinitelyNotProject3#15]
It is unclear how to integrate this method with the frontend. The lambda function that must be provided must take a BoardPosition object and return a SpaceStatus object. However, there is no straightforward way to deduce what exists at given board position with our architecture. 

Presumably, we must look up position using some GameBoard Object, allowing us to get the piece at that location. Still, this doesn't give a straightforward path to determining ownership. It may make more sense to have a BoardPosition object know what it contains.

**Comment by zjcers** [comment]
Sorry, shouldn't have made ChessPiece.PossibleMoves public. Use ChessGame.PossibleMoves.
