### ISSUE TITLE
Unity uses way too much CPU when a piece is selected

### ISSUE THREAD

**Issue by zjcers** [EECS448-KitchenUtensils/DefinitelyNotProject3#32]
We're probably doing something really expensive every frame when a piece is selected. This is not a bug per se, but there's no reason I should lag on a brand new Ryzen processor. It's chess.

**Comment by zjcers** [comment]
Seems to happen whenever it's running upon further inspection.

**Comment by jackdweber** [comment]
So at all times or just when piece selected? @zjcers

**Comment by jackdweber** [comment]
After re-doing the frontend for use with Arby, it didn't need to be checked.
